### ISSUE TITLE
Requested formatting changes

### ISSUE THREAD

**Issue by lkuper** [lkuper/dissertation#2]
- [x] The month and year on your title page should be the month and year in which the degree will actually be awarded. Please change the month and year on your title page to September 2015.
- [x] On the abstract page, your name should be place as the first item on the page, centered. Under your name should be the dissertation title, either in all capital letters or underlined. Remove your name after the title.
- [x] Black font should be used throughout the dissertation with the only exception being areas where a different font color serves a purpose in explaining or highlighting some aspect of the research/dissertation in a way black font could not. Change all non-black font which serves no other purpose to black font.
- [x] Add an entry for your curriculum vita (CV) to the table of contents. The CV should be the last item in your dissertation and listed last on the table of contents. Since CV pages should not have a page number, the table of contents entry for it should note only the presence of the CV at the end with no page number indicated.
- [x] Remove all blank pages from the dissertation.
- [x] Remove the small heading from page 135 or place it on all the bibliography pages. It is not used on other bibliography pages and we ask that formatting be consistent throughout.
- [x] On the CV, remove the header and page number. CV pages are not numbered and headers are not used in dissertations. Change the month of your PhD to September on the CV.

**Comment by lkuper** [comment]
Resubmitting...

**Comment by lkuper** [comment]
Accepted!

**Comment by rrnewton** [comment]
Woo!  As Tori goes through the thesis I am just now checking out some of these fancy illustrations you've added -- very nice!
